// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bicfjwathbmfcxkltxlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpY2Zqd2F0aGJtZmN4a2x0eGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjI1NjYsImV4cCI6MjA2Mjc5ODU2Nn0._-_KAjgbMI_WnumSCb2b8msG-saZwmhpyDeZGCdoXWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);